- name: cron environment
  cron:
    name: 'env {{ item }}'
    job: ''
    minute: '{{ item }}'
    hour: ''
    day: ''
    weekday: ''
    month: ''
  with_items:
    - 'SHELL=/bin/bash'
    - 'HOME={{ ansible_env.HOME }}'

