- file: path=~/.{{ item }} state=directory
  with_items:
    - innotop
    - ipython
    - ipython/profile_default
    - ipython/profile_default/startup

- file: src={{ ansible_env.PWD }}/roles/julius_mac/files/dotfiles/{{ item }}
        path=~/.{{ item }}
        state=link
  with_items:
    - gitconfig
    - gitignore_global
    - python_startup
    - ssh/config
    - ansible.cfg
    - ipython/profile_default/startup/00-imports.py

- copy: src=dotfiles/innotop/innotop.conf
        dest=~/.innotop/innotop.conf
        force=no  # Only if it doesn't exist

