- name: OS X Global | Show all extensions
  osx_defaults: key=AppleShowAllExtensions bool=true

- name: OS X Global | Tab goes through all controls on dialogs
  osx_defaults: key=AppleKeyboardUIMode int=3

- name: Dock | Size
  osx_defaults: domain=com.apple.dock key=tilesize int=48
  notify: kill dock

- name: Finder | Home folder on new windows
  osx_defaults: domain=com.apple.finder key=NewWindowTarget string=PfHm
  notify: kill finder

- name: Finder | Disable slow animations on shift
  osx_defaults: domain=com.apple.finder key=FXEnableSlowAnimation bool=no
  notify: kill finder

- name: Finder | Quicklook hide on defocus
  osx_defaults: domain=com.apple.finder key=QLHidePanelOnDeactivate bool=true
  notify: kill finder

- name: Finder | Full paths in title
  osx_defaults: domain=com.apple.finder key=_FXShowPosixPathInTitle bool=yes
  notify: kill finder

- name: Terminal | Get current settings
  command: plutil -convert xml1 -o - ~/Library/Preferences/com.apple.Terminal.plist
  changed_when: false
  register: terminal_settings

- name: Terminal | Theme
  when: "'<key>Seporaitis</key>' not in terminal_settings.stdout"
  command: open {{ ansible_env.PWD }}/roles/julius_mac/files/Seporaitis.terminal

- name: Terminal | My theme everywhere
  osx_defaults: domain=com.apple.terminal key="{{ item }}" string="Seporaitis"
  with_items:
    - Default Window Settings
    - Startup Window Settings

- command: chflags nohidden ~/Library/
